# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    grafana_dashboard: "1"
data:
  gpu-usage-dashboard.json: |
{{ .Files.Get "dashboards/gpu-usage-dashboard.json" | indent 4 }}
  gpu-usage-dashboard-lite.json: |
{{ .Files.Get "dashboards/gpu-usage-dashboard-lite.json" | indent 4 }}